### ISSUE TITLE
Big performance issue

### ISSUE THREAD

**Issue by massens** [evgenygarl/flag-icons-rails#28]
Hi there, 

I tried using this gem and noticed a direct increase of page response time of +1s. 

Best,
Marc

**Comment by gr8bit** [comment]
You will most likely experience the sass compiling. This won't happen on production (with asset precompiling) and even in development it will only slow down your requests if you change scss files causing a recompile. It's no problem with the gem itself as far as I understand. :)

Best,
Niklas
