### ISSUE TITLE
Sass::SyntaxError: Undefined mixin 'flag-icon'  - Error  While Pre-compiling Assets.

### ISSUE THREAD

**Issue by grichardomi** [evgenygarl/flag-icons-rails#30]
Trying to pre-compile assets in production throws error:

rails aborted!
Sass::SyntaxError: Undefined mixin 'flag-icon'.
/home/solidus/vendor/bundle/ruby/2.5.0/gems/flag-icons-rails-2.5.0/app/assets/stylesheets/flag-icon-sass/flag-icon-list.scss:1:in `flag-icon'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/flag-icons-rails-2.5.0/app/assets/stylesheets/flag-icon-sass/flag-icon-list.scss:1
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:352:in `block in visit_mixin'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/stack.rb:98:in `block in with_mixin'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/stack.rb:135:in `with_frame'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/stack.rb:98:in `with_mixin'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/tree/visitors/perform.rb:350:in `visit_mixin'
/home/solidus/vendor/bundle/ruby/2.5.0/gems/sass-3.5.5/lib/sass/tree/visitors/base.rb:36:in `visit'

**application.css:**
*= require flag-icon
 *= require_tree .
 *= require_self
 */

Does anyone have any clues?

**Comment by hleow0707** [comment]
having the same issue here any ideas?

**Comment by gr8bit** [comment]
> having the same issue here any ideas?

Am not having that issue, the mixin `flag-icon` is defined in this project's file `flag-icon-base.scss`, which is included in the `flag-icon.scss` file you require in your appppppppppholdonasecond. Your file should be named `application.*s*css`, is that the case?

**Comment by gr8bit** [comment]
Closing as this is nearly 2 years old.
