### ISSUE TITLE
'element' option does not work properly

### ISSUE THREAD

**Issue by rhugo** [evgenygarl/flag-icons-rails#38]
```
flag_icon('es', element: :sup, class: 'custom-flag-icon')
#=> <span element="sup" class="flag-icon flag-icon-es  custom-flag-icon"></span>
```

**Comment by gr8bit** [comment]
This feature currently is in master branch only and hasn't been released yet.
As flag-icons-rails uses the same versions as flag-icon-css (where the flags are from), so 3.4.6 is the current version.
We have two options:
1. I build and release a 3.4.6.1 version to rubygems.
2. You reference the master branch in your Gemfile like this until the next version comes out: `gem 'flag-icons-rails', git: 'https://github.com/evgenygarl/flag-icons-rails'`

I'd prefer number 2 to not change the current versioning if it can be avoided.

**Comment by gr8bit** [comment]
@rhugo Version `3.4.6.1` released.
